version: '3'
networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    networks:
      - laravel
    ports:
      - "8088:80" 
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER : root
      MYSQL_PASSWORD: se.bkiprono
      MYSQL_ROOT_PASSWORD: se.bkiprono
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pma
      networks:
        - laravel
      environment:
        PMA_HOST: mysql
#        PMA_USER: root
        PMA_PASSWORD: se.bkiprono
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - "8081:80"
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  
